version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mini_url
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      [
        "redis-server",
        "--user",
        "default",
        "on",
        "nopass",
        "sanitize-payload",
        "~*",
        "&*",
        "+@all",
        "--user",
        "redis",
        "on",
        ">redis",
        "sanitize-payload",
        "~*",
        "&*",
        "+@all",
      ]

volumes:
  postgres_data:
  redis_data:
